<footer>
  <div class="main">
    <div class="row-1">
      <div class="container_24">
        <div class="wrapper_bottom">
          <div class="grid_16">
            <ul class="list-services">
              <li><a class="tooltips" title="Facebook" href="#"><img src="images/facebook.png" alt=""/></a></li>
              <li><a class="tooltips" title="Flickr" href="#"><img src="images/flickr.png" alt=""/></a></li>
              <li><a class="tooltips" title="Twitter" href="#"><img src="images/twitter.png" alt=""/></a></li>
              <li><a class="tooltips" title="RSS" href="#"><img src="images/rss.png" alt=""/></a></li>
            </ul>
          </div>
          <div class="grid_8">
            <form id="subscribe-form" action="" method="post" enctype="multipart/form-data">
              <fieldset>
                <div class="wrapper">
                  <input type="text" value="-enter your e-mail here-" onFocus="if(this.value=='-enter your e-mail here-'){this.value=''}" onBlur="if(this.value==''){this.value='-enter your e-mail here-'}"/>
                  <a href="#" onClick="document.getElementById('subscribe-form').submit()">Subscribe</a>
                </div>
              </fieldset>
            </form>
          </div>
        </div>
      </div>
      <div class="angle-left"></div>
      <div class="angle-right"></div>
    </div>
    <div class="row-2">
      <div class="container_24">
        <div class="bg">
          <div class="wrapper">
            <div class="grid_24">
              <div class="indent">
                Martin Verdugo &copy; 2014 &nbsp;:&nbsp; Located in <a class="link-2" href="los_barriles.php">Los Barriles,</a> Baja California Sur, Mexico -- <a class="link-2" href="contact.html">Contact Us</a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
