<nav>
  <ul class="menu">
    <li class="first"><a class="item" href="index.php">HOTEL</a>
      <!--
    <ul>
         <li><a href="#">Rates</a></li>
          <li><a href="#">Reservations</a></li>
          <li><a href="index-6.html">Contacts</a></li>
      </ul>
      -->
    </li>
    <li><a class="item" href="rooms.php">ROOMS</a></li>
    <li><a class="item" href="fishing_packages.php">FISHING PACKAGES</a></li>
    <li><a class="item" href="wind_surfing.php">WINDSURFING</a></li>
    <li><a class="item" href="activities.php">ACTIVITIES</a></li>
    <li><a class="item" href="maps.php">MAP</a></li>
    <li><a class="item" href="photos.php">PHOTOS</a></li>
    <li><a class="item" href="http://reports.verdugosbeachresort.com">REPORTS</a></li>
    <li><a class="item" href="contact.php">CONTACT</a></li>
  </ul>
</nav>
