<div class="suf">
  <div class="box">
    <div class="wrapper">
      <figure class="img-indent3 frame"><img src="images/thumb-contact-us.jpg" alt=""/></figure>
      <div class="extra-wrap">
        <h4>Contact Us</h4>
        <a class="link-1" href="contact.php">Click Here</a>
      </div>
    </div>
  </div>
  <div class="box">
    <div class="wrapper">
      <figure class="img-indent3 frame"><img src="images/thumb-rooms-rates.jpg" alt=""/></figure>
      <div class="extra-wrap">
        <h4>Rooms &amp; Rates</h4>
        <a class="link-1" href="rooms.php">Click Here</a>
      </div>
    </div>
  </div>
  <div class="box">
    <div class="wrapper">
      <figure class="img-indent3 frame"><img src="images/thumb-fishing-packages.jpg" alt=""/></figure>
      <div class="extra-wrap">
        <h4>Fishing Packages</h4>
        <a class="link-1" href="fishing_packages.php">Click Here</a>
      </div>
    </div>
  </div>
  <div class="box">
    <div class="wrapper">
      <figure class="img-indent3 frame"><img src="images/thumb-activities.jpg" alt=""/></figure>
      <div class="extra-wrap">
        <h4>Activities</h4>
        <a class="link-1" href="activities.php">Click Here</a>
      </div>
    </div>
  </div>
  <div class="indent-bot">
    <div class="box">
      <div class="wrapper">
        <figure class="img-indent3 frame"><img src="images/thumb-mapweather.jpg" alt=""/></figure>
        <div class="extra-wrap">
          <h4>Map &amp; Transportation</h4>
          <a class="link-1" href="maps.php">Click Here</a>
        </div>
      </div>
    </div>
  </div>
</div>


